/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { AiStudioCreateNestedManyWithoutVirtualArtistsInput } from "./AiStudioCreateNestedManyWithoutVirtualArtistsInput";
import { ValidateNested, IsOptional, IsString, IsEnum } from "class-validator";
import { Type } from "class-transformer";
import { EnumVirtualArtistGenre } from "./EnumVirtualArtistGenre";
import { MusicChallengeCreateNestedManyWithoutVirtualArtistsInput } from "./MusicChallengeCreateNestedManyWithoutVirtualArtistsInput";
import { RecordLabelCreateNestedManyWithoutVirtualArtistsInput } from "./RecordLabelCreateNestedManyWithoutVirtualArtistsInput";
import { VoiceCustomizationWhereUniqueInput } from "../../voiceCustomization/base/VoiceCustomizationWhereUniqueInput";

@InputType()
class VirtualArtistCreateInput {
  @ApiProperty({
    required: false,
    type: () => AiStudioCreateNestedManyWithoutVirtualArtistsInput,
  })
  @ValidateNested()
  @Type(() => AiStudioCreateNestedManyWithoutVirtualArtistsInput)
  @IsOptional()
  @Field(() => AiStudioCreateNestedManyWithoutVirtualArtistsInput, {
    nullable: true,
  })
  aiStudios?: AiStudioCreateNestedManyWithoutVirtualArtistsInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  description?: string | null;

  @ApiProperty({
    required: false,
    enum: EnumVirtualArtistGenre,
  })
  @IsEnum(EnumVirtualArtistGenre)
  @IsOptional()
  @Field(() => EnumVirtualArtistGenre, {
    nullable: true,
  })
  genre?: "Option1" | null;

  @ApiProperty({
    required: false,
    type: () => MusicChallengeCreateNestedManyWithoutVirtualArtistsInput,
  })
  @ValidateNested()
  @Type(() => MusicChallengeCreateNestedManyWithoutVirtualArtistsInput)
  @IsOptional()
  @Field(() => MusicChallengeCreateNestedManyWithoutVirtualArtistsInput, {
    nullable: true,
  })
  musicChallenges?: MusicChallengeCreateNestedManyWithoutVirtualArtistsInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  name?: string | null;

  @ApiProperty({
    required: false,
    type: () => RecordLabelCreateNestedManyWithoutVirtualArtistsInput,
  })
  @ValidateNested()
  @Type(() => RecordLabelCreateNestedManyWithoutVirtualArtistsInput)
  @IsOptional()
  @Field(() => RecordLabelCreateNestedManyWithoutVirtualArtistsInput, {
    nullable: true,
  })
  recordLabels?: RecordLabelCreateNestedManyWithoutVirtualArtistsInput;

  @ApiProperty({
    required: false,
    type: () => VoiceCustomizationWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => VoiceCustomizationWhereUniqueInput)
  @IsOptional()
  @Field(() => VoiceCustomizationWhereUniqueInput, {
    nullable: true,
  })
  voiceCustomization?: VoiceCustomizationWhereUniqueInput | null;
}

export { VirtualArtistCreateInput as VirtualArtistCreateInput };
